__include__: [
  '../../dataset/my_coco_detection.yml',
  '../../runtime.yml',
  '../include/my_dataloader.yml',
  '../include/my_optimizer.yml',
  '../include/my_dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_l_obj2coco


DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 4
  freeze_norm: True

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00001  # Явно указываем число вместо 1e-5
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.0  # Указываем 0.0 вместо 0.

  lr: 0.00005  # Явно указываем число вместо 5e-5
  betas: [0.9, 0.999]
  weight_decay: 0.0005


epochs: 20 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 30
  collate_fn:
    stop_epoch: 30
    ema_restart_decay: 0.9999
    base_size_repeat: 4

ema:
  warmups: 100

lr_warmup_scheduler:
  warmup_duration: 100
