use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 100
  start: 0


epochs: 20
clip_max_norm: 0.1


optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00005
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.0

  lr: 0.0003
  betas: [0.9, 0.999]
  weight_decay: 0.0005


lr_scheduler:
  type: CosineAnnealingLR
  T_max: 72
  eta_min: 0.000001

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 100
